config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :users, only: [:update]
  
  resources :topics do 
    resources :posts, except: [:index] 
  end

  resources :posts, only: [] do 
    resources :comments, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'

  root to: 'welcome#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.paginate(page: params[:page], per_page: 10)
    authorize @topics
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.paginate(page: params[:page], per_page: 10)
    authorize @topic
  end

  def new
    @topic = Topic.new
    authorize @topic
  end 

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      flash[:notice] = "Topic was saved."
      redirect_to @topic
    else
      flash[:error] = "There was an error saving the topic. Please try again."
      render :new
    end 
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)  
      redirect_to @topic
    else
      flash[:error] = "There was an error updating the topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic. Please try again."
      render :show
    end
  end
  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guideline for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insulte dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topic
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1> Topics </h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>  
      </div>
    <% end %>
    <%= will_paginate @topics, @batch_count, @page %>
  </div>
  <div class="col-md-4">
    <% if policy(Topic.new).create? %>
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guideline for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insulte dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public%> Public topic
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1> <%= markdown @topic.name %> </h1>
<p class="lead"><%= markdown @topic.description %></p>  
<% if policy(@topic).create? %>
  <%= link_to "Edit topic", edit_topic_path(@topic), class: 'btn btn-success' %>  
<% end %>
<br>
<div class="row">
  <div class="col-md-8">
    <% @posts.each do |post| %>
      <div class="media">
        <%= render partial: 'votes/voter', locals: { post: post} %>
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to (markdown post.title), [@topic, post] %>
          </h4>
          <small>
            <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br/>
            <%= post.comments.count %> Comments
          </small>
          <br/>
          <%= image_tag(post.image.thumb.url) if post.image? %>
        </div>  
      </div>
    <% end %>
    <%= will_paginate @posts %>
  </div>
  <div class="col-md-4">
    <% if policy(Post.new).create? %>
      <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
    <% end %>    
    <% if policy(@topic).destroy? %>
      <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this topic?' } %>
    <% end %>    
  </div>
</div>  