config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :users, only: [:update]
  
  resources :topics do 
    resources :posts, except: [:index] 
  end

  resources :posts, only: [] do 
    resources :comments, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  default_scope { order('rank DESC')}

  scope :ordered_by_title, -> { order('title ASC')}

  scope :ordered_by_reverse_created_at, -> {order('created_at DESC')}

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  mount_uploader :image, ImageUploader

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) 
    new_rank = points + age_in_days

    update_attributes({rank: new_rank})
  end

  def markdown_title 
    render_as_markdown title
  end

  def markdown_body 
    render_as_markdown body
  end

  def create_vote
    vote = user.votes.create(value: 1, post: self)
  end

  private

  def render_as_markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    @comments = @post.comments.all
    authorize @post
  end

  def new
    @post = Post.new
    @topic = Topic.find(params[:topic_id])
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic

    authorize @post

    if @post.save
      @post.create_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])

    authorize @post
    
    if q@post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "Thre was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    title = @post.title

    authorize @post
    
    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post. Please try again."
      render :show
    end
  end
  private 

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
  <div class="alert alert-danger">
    <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
    <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class=<%= form_group_tag(post.errors) %>>
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control', placeholder: "Enter post title" %>
  </div>
  <div class=<%= form_group_tag(post.errors) %>>
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', plcaholder: "Enter post body" %>
  </div>
  <% if post.image? %>
    <div class="form-group">
      <p>Current image</p>
      <%= image_tag( post.image.thumb.url ) %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A"</li>
      <li>The incessant use of hashtas will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A"</li>
      <li>The incessant use of hashtas will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8">
    <%= render partial: 'votes/voter', locals: { post: @post} %>
    <h1><%= @post.markdown_title %></h1>
    <small>
      <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    </small>
    <%= image_tag(@post.image.url) if @post.image? %>
    <p><%= @post.markdown_body %></p>
    <br>
    <%= render partial: 'comments/comment', collection: @comments %>
    <br>
    <% if policy(Comment.new).create? %>
      <%= render partial: 'comments/form', locals: { post: @post, comment: @post.comments.new } %>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
    <% end %>  
    <% if policy(@post).destroy? %>
      <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
    <% end %>
    <div>
      <h3><%= pluralize(@post.points, 'point') %></h3>
      <small>
        <%= pluralize(@post.up_votes, 'up vote') %>,
        <%= pluralize(@post.down_votes, 'down vote') %>
      </small>
    </div>  
  </div>
</div>